### ISSUE TITLE
Flow failing with graphql@^14.5.3:

### ISSUE THREAD

**Issue by kedarguy** [graphql/graphql-js#2141]
I am getting the following errors when running flow:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/jsutils/memoize3.js.flow:18:29

Cannot call cache0.get with a1 bound to key because read-only array type [1] is incompatible with object type [2].

     node_modules/graphql/jsutils/memoize3.js.flow
 [1]  11│ >(fn: (A1, A2, A3) => R): (A1, A2, A3) => R {
      12│   let cache0;
      13│
      14│   function memoized(a1, a2, a3) {
      15│     if (!cache0) {
      16│       cache0 = new WeakMap();
      17│     }
      18│     let cache1 = cache0.get(a1);
      19│     let cache2;
      20│     if (cache1) {
      21│       cache2 = cache1.get(a2);

     /tmp/flow/flowlib_3fce4660/core.js
 [2] 564│ declare class WeakMap<K: {}, V> extends $ReadOnlyWeakMap<K, V> {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/jsutils/memoize3.js.flow:21:27

Cannot call cache1.get with a2 bound to key because read-only array type [1] is incompatible with object type [2].

     node_modules/graphql/jsutils/memoize3.js.flow
 [1]  11│ >(fn: (A1, A2, A3) => R): (A1, A2, A3) => R {
        :
      18│     let cache1 = cache0.get(a1);
      19│     let cache2;
      20│     if (cache1) {
      21│       cache2 = cache1.get(a2);
      22│       if (cache2) {
      23│         const cachedValue = cache2.get(a3);
      24│         if (cachedValue !== undefined) {

     /tmp/flow/flowlib_3fce4660/core.js
 [2] 564│ declare class WeakMap<K: {}, V> extends $ReadOnlyWeakMap<K, V> {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/jsutils/memoize3.js.flow:23:40

Cannot call cache2.get with a3 bound to key because read-only array type [1] is incompatible with object type [2].

     node_modules/graphql/jsutils/memoize3.js.flow
 [1]  11│ >(fn: (A1, A2, A3) => R): (A1, A2, A3) => R {
        :
      20│     if (cache1) {
      21│       cache2 = cache1.get(a2);
      22│       if (cache2) {
      23│         const cachedValue = cache2.get(a3);
      24│         if (cachedValue !== undefined) {
      25│           return cachedValue;
      26│         }

     /tmp/flow/flowlib_3fce4660/core.js
 [2] 564│ declare class WeakMap<K: {}, V> extends $ReadOnlyWeakMap<K, V> {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/jsutils/memoize3.js.flow:30:18

Cannot call cache0.set with a1 bound to key because read-only array type [1] is incompatible with object type [2].

     node_modules/graphql/jsutils/memoize3.js.flow
 [1]  11│ >(fn: (A1, A2, A3) => R): (A1, A2, A3) => R {
        :
      27│       }
      28│     } else {
      29│       cache1 = new WeakMap();
      30│       cache0.set(a1, cache1);
      31│     }
      32│     if (!cache2) {
      33│       cache2 = new WeakMap();

     /tmp/flow/flowlib_3fce4660/core.js
 [2] 564│ declare class WeakMap<K: {}, V> extends $ReadOnlyWeakMap<K, V> {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/jsutils/memoize3.js.flow:34:18

Cannot call cache1.set with a2 bound to key because read-only array type [1] is incompatible with object type [2].

     node_modules/graphql/jsutils/memoize3.js.flow
 [1]  11│ >(fn: (A1, A2, A3) => R): (A1, A2, A3) => R {
        :
      31│     }
      32│     if (!cache2) {
      33│       cache2 = new WeakMap();
      34│       cache1.set(a2, cache2);
      35│     }
      36│     const newValue = fn(a1, a2, a3);
      37│     cache2.set(a3, newValue);

     /tmp/flow/flowlib_3fce4660/core.js
 [2] 564│ declare class WeakMap<K: {}, V> extends $ReadOnlyWeakMap<K, V> {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/jsutils/memoize3.js.flow:37:16

Cannot call cache2.set with a3 bound to key because read-only array type [1] is incompatible with object type [2].

     node_modules/graphql/jsutils/memoize3.js.flow
 [1]  11│ >(fn: (A1, A2, A3) => R): (A1, A2, A3) => R {
        :
      34│       cache1.set(a2, cache2);
      35│     }
      36│     const newValue = fn(a1, a2, a3);
      37│     cache2.set(a3, newValue);
      38│     return newValue;
      39│   }
      40│

     /tmp/flow/flowlib_3fce4660/core.js
 [2] 564│ declare class WeakMap<K: {}, V> extends $ReadOnlyWeakMap<K, V> {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/polyfills/flatMap.js.flow:12:30

Cannot get Array.prototype.flatMap because property flatMap is missing in Array [1].

     node_modules/graphql/polyfills/flatMap.js.flow
       9│ // $FlowFixMe
      10│ const flatMap = Array.prototype.flatMap
      11│   ? function(list, fn) {
      12│       return Array.prototype.flatMap.call(list, fn);
      13│     }
      14│   : function(list, fn) {
      15│       let result = [];

     /tmp/flow/flowlib_3fce4660/core.js
 [1] 238│ declare class Array<T> extends $ReadOnlyArray<T> {



Found 7 errors
error Command failed with exit code 2.
```

**Comment by IvanGoncharov** [comment]
@kedarguy I just released `14.5.4` that should resolve some of the errors, however I can reproduce `Cannot call cache0.get with a1 bound to key because read-only array type [1] is incompatible with object type [2].` even on older Flow versions.
Can you please retest it with `14.5.4` and if you still have errors please provide more details about your projects, e.g. Flow version, the content of `.flowconfig`.
Also, it would be great if you can create a sample repo that reproduces this problem.

**Comment by IvanGoncharov** [comment]
@kedarguy Can you please retest with `14.5.4`?

**Comment by kedarguy** [comment]
Actually got a lot more errors after upgrading 

We are running a bit old version of flow, and maybe this is causing some of the problems
`"flow-bin": "^0.87.0",`

initially after upgrading I got these errors: 

```
yarn run v1.16.0
$ flow check
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/components/htz-components/src/components/AdBlock/AdBlockRedirect.js:9:28

Cannot assign template string to USER because:
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property arguments of array
   element of property directives of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property name.loc.source of array element of property arguments of
   array element of property directives of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property value.loc.source of array element of property arguments of
   array element of property directives of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property fields of array
   element of property value.values of array element of property arguments of array element of property directives of
   array element of property definitions.
 • Source [1] is incompatible with Source [2] in property value.loc.source of array element of property fields of
   array element of property value.values of array element of property arguments of array element of property directives
   of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property directives of array
   element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property arguments of array
   element of property fields of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property fields of array
   element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property operationTypes of
   array element of property definitions.
 • Source [1] is incompatible with Source [2] in property selectionSet.loc.source of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property
   selectionSet.selections of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property alias.loc.source of array element of property
   selectionSet.selections of array element of property selectionSet.selections of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property arguments of array
   element of property selectionSet.selections of array element of property selectionSet.selections of array element of
   property definitions.
 • Source [1] is incompatible with Source [2] in property value.loc.source of array element of property arguments of
   array element of property selectionSet.selections of array element of property selectionSet.selections of array
   element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property fields of array
   element of property value.values of array element of property arguments of array element of property
   selectionSet.selections of array element of property selectionSet.selections of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property value.loc.source of array element of property fields of
   array element of property value.values of array element of property arguments of array element of property
   selectionSet.selections of array element of property selectionSet.selections of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property directives of array
   element of property selectionSet.selections of array element of property selectionSet.selections of array element of
   property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property
   selectionSet.selections of array element of property selectionSet.selections of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property typeCondition.loc.source of array element of property
   selectionSet.selections of array element of property selectionSet.selections of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property typeCondition.loc.source of array element of property
   selectionSet.selections of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property values of array
   element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property variableDefinitions
   of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property type.loc.source of array element of property
   variableDefinitions of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property type.type.type.loc.source of array element of property
   variableDefinitions of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source.

     packages/components/htz-components/src/components/AdBlock/AdBlockRedirect.js
      6│ import type { DocumentNode, } from 'graphql/language/ast';
      7│ import ApolloConsumer from '../ApolloBoundary/ApolloConsumer';
      8│
      9│ const USER: DocumentNode = gql`
     10│   query getUser {
     11│     user @client {
     12│       type
     13│     }
     14│   }
     15│ `;
     16│
     17│ type State = {
     18│   hasListener: boolean,

     node_modules/graphql/language/ast.js.flow
 [1] 34│   +source: Source,

     packages/components/htz-components/node_modules/graphql/language/ast.js.flow
 [2] 34│   +source: Source,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/components/htz-components/src/components/List/ListDataGetter.js:15:35

Cannot assign template string to GET_SECTION because:
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property arguments of array
   element of property directives of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property name.loc.source of array element of property arguments of
   array element of property directives of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property value.loc.source of array element of property arguments of
   array element of property directives of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property fields of array
   element of property value.values of array element of property arguments of array element of property directives of
   array element of property definitions.
 • Source [1] is incompatible with Source [2] in property value.loc.source of array element of property fields of
   array element of property value.values of array element of property arguments of array element of property directives
   of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property directives of array
   element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property arguments of array
   element of property fields of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property fields of array
   element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property operationTypes of
   array element of property definitions.
 • Source [1] is incompatible with Source [2] in property selectionSet.loc.source of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property
   selectionSet.selections of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property alias.loc.source of array element of property
   selectionSet.selections of array element of property selectionSet.selections of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property arguments of array
   element of property selectionSet.selections of array element of property selectionSet.selections of array element of
   property definitions.
 • Source [1] is incompatible with Source [2] in property value.loc.source of array element of property arguments of
   array element of property selectionSet.selections of array element of property selectionSet.selections of array
   element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property fields of array
   element of property value.values of array element of property arguments of array element of property
   selectionSet.selections of array element of property selectionSet.selections of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property value.loc.source of array element of property fields of
   array element of property value.values of array element of property arguments of array element of property
   selectionSet.selections of array element of property selectionSet.selections of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property directives of array
   element of property selectionSet.selections of array element of property selectionSet.selections of array element of
   property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property
   selectionSet.selections of array element of property selectionSet.selections of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property typeCondition.loc.source of array element of property
   selectionSet.selections of array element of property selectionSet.selections of array element of property
   definitions.
 • Source [1] is incompatible with Source [2] in property typeCondition.loc.source of array element of property
   selectionSet.selections of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property values of array
   element of property definitions.
 • Source [1] is incompatible with Source [2] in property loc.source of array element of property variableDefinitions
   of array element of property definitions.
 • Source [1] is incompatible with Source [2] in property type.loc.source of array element of property
   variableDefinitions of array element of property definitions.
 • ... 2 more errors.

     packages/components/htz-components/src/components/List/ListDataGetter.js
     12│ import type { ListDataType, } from '../../flowTypes/ListDataType';
     13│ import ListPlaceholder from '../ListPlaceholder/ListPlaceholder';
     14│
     15│ const GET_SECTION: DocumentNode = gql`
     16│   query GetSection {
     17│     articleSection @client {
     18│       url
     19│     }
     20│   }
     21│ `;
     22│
     23│ type ListComponentProps = {
     24│   // generalized this to avoid complexity of dfp/teaser/clicktracker

     node_modules/graphql/language/ast.js.flow
 [1] 34│   +source: Source,

     packages/components/htz-components/node_modules/graphql/language/ast.js.flow
 [2] 34│   +source: Source,



... 106 more errors (only 50 out of 156 errors displayed)
To see all errors, re-run Flow with --show-all-errors
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Then I added `.*/node_modules/graphql/language/ast\.js\.flow` to the flowignore file, and I get the following errors:

```
yarn run v1.16.0
$ flow check
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/language/printer.js.flow:12:21

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to printDocASTReducer [3].

     node_modules/graphql/language/printer.js.flow
      9│  * formatting rules.
     10│  */
     11│ export function print(ast: ASTNode): string {
 [3] 12│   return visit(ast, { leave: printDocASTReducer });
     13│ }
     14│
     15│ // TODO: provide better type coverage in future

     node_modules/graphql/language/visitor.js.flow
 [1] 15│   | EnterLeave<
     16│       | VisitFn<Nodes>
     17│       | ShapeMap<KindToNode, <Node>(Node) => VisitFn<Nodes, Node>>,
     18│     >
 [2] 19│   | ShapeMap<
     20│       KindToNode,
     21│       <Node>(Node) => VisitFn<Nodes, Node> | EnterLeave<VisitFn<Nodes, Node>>,
     22│     >;


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/type/validate.js.flow:365:9

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

 [1][2]  91│     nodes?: $ReadOnlyArray<?ASTNode> | ?ASTNode,
           :
        362│     if (!objectField) {
        363│       context.reportError(
        364│         `Interface field ${iface.name}.${fieldName} expected but ${object.name} does not provide it.`,
    [3] 365│         [ifaceField.astNode, ...getAllNodes(object)],
        366│       );
        367│       continue;
        368│     }


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/type/validate.js.flow:377:9

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

 [1][2]  91│     nodes?: $ReadOnlyArray<?ASTNode> | ?ASTNode,
           :
        374│         `Interface field ${iface.name}.${fieldName} expects type ` +
        375│           `${inspect(ifaceField.type)} but ${object.name}.${fieldName} ` +
        376│           `is type ${inspect(objectField.type)}.`,
    [3] 377│         [
        378│           ifaceField.astNode && ifaceField.astNode.type,
        379│           objectField.astNode && objectField.astNode.type,
        380│         ],
        381│       );
        382│     }
        383│


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/type/validate.js.flow:393:11

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

 [1][2]  91│     nodes?: $ReadOnlyArray<?ASTNode> | ?ASTNode,
           :
        390│       if (!objectArg) {
        391│         context.reportError(
        392│           `Interface field argument ${iface.name}.${fieldName}(${argName}:) expected but ${object.name}.${fieldName} does not provide it.`,
    [3] 393│           [ifaceArg.astNode, objectField.astNode],
        394│         );
        395│         continue;
        396│       }


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/type/validate.js.flow:407:11

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

 [1][2]  91│     nodes?: $ReadOnlyArray<?ASTNode> | ?ASTNode,
           :
        404│             `expects type ${inspect(ifaceArg.type)} but ` +
        405│             `${object.name}.${fieldName}(${argName}:) is type ` +
        406│             `${inspect(objectArg.type)}.`,
    [3] 407│           [
        408│             ifaceArg.astNode && ifaceArg.astNode.type,
        409│             objectArg.astNode && objectArg.astNode.type,
        410│           ],
        411│         );
        412│       }
        413│


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/type/validate.js.flow:424:11

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

 [1][2]  91│     nodes?: $ReadOnlyArray<?ASTNode> | ?ASTNode,
           :
        421│       if (!ifaceArg && isRequiredArgument(objectArg)) {
        422│         context.reportError(
        423│           `Object field ${object.name}.${fieldName} includes required argument ${argName} that is missing from the Interface field ${iface.name}.${fieldName}.`,
    [3] 424│           [objectArg.astNode, ifaceField.astNode],
        425│         );
        426│       }
        427│     }


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/NoUndefinedVariables.js.flow:40:17

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/NoUndefinedVariables.js.flow
        37│                   varName,
        38│                   operation.name && operation.name.value,
        39│                 ),
    [3] 40│                 [node, operation],
        41│               ),
        42│             );
        43│           }

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/PossibleTypeExtensions.js.flow:80:13

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/PossibleTypeExtensions.js.flow
        77│               typeName,
        78│               extensionKindToTypeName(expectedKind),
        79│             ),
    [3] 80│             [defNode, node],
        81│           ),
        82│         );
        83│       }

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueArgumentNames.js.flow:31:58

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueArgumentNames.js.flow
        28│       const argName = node.name.value;
        29│       if (knownArgNames[argName]) {
        30│         context.reportError(
    [3] 31│           new GraphQLError(duplicateArgMessage(argName), [
        32│             knownArgNames[argName],
        33│             node.name,
        34│           ]),
        35│         );
        36│       } else {
        37│         knownArgNames[argName] = node.name;

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueDirectiveNames.js.flow:43:74

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueDirectiveNames.js.flow
        40│
        41│       if (knownDirectiveNames[directiveName]) {
        42│         context.reportError(
    [3] 43│           new GraphQLError(duplicateDirectiveNameMessage(directiveName), [
        44│             knownDirectiveNames[directiveName],
        45│             node.name,
        46│           ]),
        47│         );
        48│       } else {
        49│         knownDirectiveNames[directiveName] = node.name;

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueDirectivesPerLocation.js.flow:62:76

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueDirectivesPerLocation.js.flow
        59│           if (uniqueDirectiveMap[directiveName]) {
        60│             if (knownDirectives[directiveName]) {
        61│               context.reportError(
    [3] 62│                 new GraphQLError(duplicateDirectiveMessage(directiveName), [
        63│                   knownDirectives[directiveName],
        64│                   directive,
        65│                 ]),
        66│               );
        67│             } else {
        68│               knownDirectives[directiveName] = directive;

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueEnumValueNames.js.flow:65:15

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueEnumValueNames.js.flow
        62│           context.reportError(
        63│             new GraphQLError(
        64│               duplicateEnumValueNameMessage(typeName, valueName),
    [3] 65│               [valueNames[valueName], valueDef.name],
        66│             ),
        67│           );
        68│         } else {

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueFieldDefinitionNames.js.flow:72:15

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueFieldDefinitionNames.js.flow
        69│           context.reportError(
        70│             new GraphQLError(
        71│               duplicateFieldDefinitionNameMessage(typeName, fieldName),
    [3] 72│               [fieldNames[fieldName], fieldDef.name],
        73│             ),
        74│           );
        75│         } else {

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueFragmentNames.js.flow:25:72

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueFragmentNames.js.flow
        22│       const fragmentName = node.name.value;
        23│       if (knownFragmentNames[fragmentName]) {
        24│         context.reportError(
    [3] 25│           new GraphQLError(duplicateFragmentNameMessage(fragmentName), [
        26│             knownFragmentNames[fragmentName],
        27│             node.name,
        28│           ]),
        29│         );
        30│       } else {
        31│         knownFragmentNames[fragmentName] = node.name;

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueInputFieldNames.js.flow:38:67

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueInputFieldNames.js.flow
        35│       const fieldName = node.name.value;
        36│       if (knownNames[fieldName]) {
        37│         context.reportError(
    [3] 38│           new GraphQLError(duplicateInputFieldMessage(fieldName), [
        39│             knownNames[fieldName],
        40│             node.name,
        41│           ]),
        42│         );
        43│       } else {
        44│         knownNames[fieldName] = node.name;

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueOperationNames.js.flow:29:15

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueOperationNames.js.flow
        26│           context.reportError(
        27│             new GraphQLError(
        28│               duplicateOperationNameMessage(operationName.value),
    [3] 29│               [knownOperationNames[operationName.value], operationName],
        30│             ),
        31│           );
        32│         } else {

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueOperationTypes.js.flow:54:72

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueOperationTypes.js.flow
        51│           );
        52│         } else if (alreadyDefinedOperationType) {
        53│           context.reportError(
    [3] 54│             new GraphQLError(duplicateOperationTypeMessage(operation), [
        55│               alreadyDefinedOperationType,
        56│               operationType,
        57│             ]),
        58│           );
        59│         } else {
        60│           definedOperationTypes[operation] = operationType;

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueTypeNames.js.flow:48:62

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueTypeNames.js.flow
        45│
        46│     if (knownTypeNames[typeName]) {
        47│       context.reportError(
    [3] 48│         new GraphQLError(duplicateTypeNameMessage(typeName), [
        49│           knownTypeNames[typeName],
        50│           node.name,
        51│         ]),
        52│       );
        53│     } else {
        54│       knownTypeNames[typeName] = node.name;

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/UniqueVariableNames.js.flow:29:68

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

        node_modules/graphql/validation/rules/UniqueVariableNames.js.flow
        26│       const variableName = node.variable.name.value;
        27│       if (knownVariableNames[variableName]) {
        28│         context.reportError(
    [3] 29│           new GraphQLError(duplicateVariableMessage(variableName), [
        30│             knownVariableNames[variableName],
        31│             node.variable.name,
        32│           ]),
        33│         );
        34│       } else {
        35│         knownVariableNames[variableName] = node.variable.name;

        node_modules/graphql/error/GraphQLError.js.flow
 [1][2] 19│     nodes?: $ReadOnlyArray<ASTNode> | ASTNode | void | null,


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/graphql/validation/rules/VariablesInAllowedPosition.js.flow:67:19

Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To
fix add a type annotation to inferred union of array element types (alternatively, provide an annotation to summarize
the array element type) [3].

```

**Comment by IvanGoncharov** [comment]
@kedarguy I switched to Flow `0.87.0` and can't reproduce these issues so Flow version isn't problem here.
It looks like you are using two versions of `graphql` that conflict with each other:
> node_modules/graphql/language/ast.js.flow
> packages/components/htz-components/node_modules/graphql/language/ast.js.flow

This isn't something we can fix in the scope of this library 😞

**Comment by kedarguy** [comment]
Thanks, fixing the conflicting versions solved most of the problems.

Im still getting the `Cannot call cache0.get with a1 bound to key because read-only array type [1] is incompatible with object type [2].` 

I will try to reproduce and update here
